name: Deploy to EC2

on:
  push:
    branches: [ feature/graalvm-native ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17'
          distribution: 'graalvm'

      - name: Create application.yml
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.APPLICATION_PROD_YML }}" > src/main/resources/application.yml

      - name: Build Native Image
        run: ./gradlew nativeCompile -x test

      - name: Transfer binary to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "build/native/nativeCompile/wiki"
          target: "/home/ubuntu"
          strip_components: 3

      - name: Deploy on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            pkill -x wiki || true
            sleep 2
            chmod +x /home/ubuntu/wiki
            nohup /home/ubuntu/wiki \
              -Dencryption.aes-key=${{ secrets.AES_KEY }} \
              > /home/ubuntu/app.log 2>&1 &
